on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - name: Esport env file
        uses: dusanmarsa/secret-content-file@master
        with:
          secret_content: 'secret'
          file_name: '.env'
          directory: './'