on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test action
    steps:
      - uses: actions/checkout@v2

      - name: Export env file
        uses: dusanmarsa/secret-content-file@master
        with:
          CONTENT: ${{secrets.SECRET_NAME}}
          FILE_NAME: '.env'

      - name: Echo .env
        run: |
          ls -la
          cat .env
