on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2

      - name: Esport env file
        uses: dusanmarsa/secret-content-file@master
        with:
          CONTENT: 'secret content'
          FILE_NAME: '.env'
          DIRECTORY: 'src'

      - name: Echo .env
        run: |
          ls -la
          echo "Dist"
          cd dist
          ls -la
          echo "Src"
          cd ../src
          ls -la
          echo "Other"
          cd ../other
          ls -la
