on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      - uses: actions/checkout@v2

      - name: Esport env file
        uses: dusanmarsa/secret-content-file@master
        with:
          CONTENT: 'secret content'
          FILE_NAME: '.env'

      - name: Echo .env
        run: |
          ls
          cd dist
          ls
          cd ../src
          ls